name: Remote IPA Update

on:
  repository_dispatch:
    types: [ipa-update]

jobs:
  trigger-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ipa_url: ${{ github.event.client_payload.ipa_url }}
      testflight: ${{ github.event.client_payload.testflight }}
      release: true
    secrets: inherit
